{% set name = "ecctl" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/elastic/ecctl/archive/v{{ version }}.tar.gz
  sha256: 8e631b888f5f28aca4684625e0ae5694b83de1829f6f4c3d20aa8ed4095c9def

# Can we get windows to work?
build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses
    - make

test:
  requires:

  commands:
    - ecctl --help
    - ecctl version | grep -F '{{ version }}'  # [not win]

about:
  home: https://www.elastic.co/
  license: Apache-2.0
  license_file:
    - LICENSE
    - licenses.txt
  summary: ecctl is the CLI for the Elasticsearch Service and Elastic Cloud Enterprise APIs.
  doc_url: https://www.elastic.co/guide/en/ecctl/current/index.html
  dev_url: https://github.com/elastic/{{ name }}

extra:
  recipe-maintainers:
    - mxr-conda
    - MatthewJanuszewski
    - oblute
